### ISSUE TITLE
Move connect americas link

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/macromarket#55]
Currently the link back to the connect americas site (for a connect americas company) is located at the bottom of their description on the left. This tends to get buried if they have a long description. Maybe we could move this to the image header? Here's an example of what I'm talking about: https://macro.market/company/ca_5051

![screen shot 2017-10-11 at 1 38 45 pm](https://user-images.githubusercontent.com/252276/31457096-bd15ab1a-ae89-11e7-8038-f3df6bbd4b1a.png)

**Comment by housegeoff** [comment]
@alexandersimoes Could the link work in the top right? On product and country pages we use that space for actionable buttons so the convention could carry over to this page as well.

**Comment by alexandersimoes** [comment]
Ya I think that's a great idea.
